### ISSUE TITLE
Does CITATION include the links? 

### ISSUE THREAD

**Issue by sishtiaq** [tomcrick/JORS2015#12]
* Recommendation VI: Should CITATION include the links? Or should they
  be spread throughout the code? Since CITATION files are typically
  not parsed as part of the scholarly record (as opposed to papers,
  which are also mentioned) is that where citations should be placed?

**Comment by tomcrick** [comment]
We should probably weave in the work of the [FORCE11 Software Citation Working Group](https://www.force11.org/group/software-citation-working-group) and their [Software Citation Principles](https://www.force11.org/software-citation-principles) (2016)

**Comment by sishtiaq** [comment]
All yours, Tom!

**Comment by hallba** [comment]
I'm not familiar with FORCE11; @tomcrick can you add this?

**Comment by tomcrick** [comment]
Will do.

**Comment by tomcrick** [comment]
Fixed by this commit: https://github.com/tomcrick/JORS2015/commit/5eef1f9e8516848c76c17dbc02d74a3c02fc017a
