### ISSUE TITLE
New title?

### ISSUE THREAD

**Issue by tomcrick** [tomcrick/JORS2015#17]
In light of the reviewer comments and today's useful issues/tweaks, should we rethink the title?

**Comment by sishtiaq** [comment]
Maybe. What title were you thinking?

**Comment by tomcrick** [comment]
Good question; something like:

"Developing Systems, Infrastructure and Culture for Reproducibility in Research"...

**Comment by sishtiaq** [comment]
Reproducibility in Research: Systems, Infrastructure, Culture.

**Comment by tomcrick** [comment]
Yep, I like that!
