### ISSUE TITLE
What are they proposing?

### ISSUE THREAD

**Issue by sishtiaq** [tomcrick/JORS2015#4]
Q. Does the paper summarise the experiences of the authors, including
reflection on the importance of the arguments and conclusions?

A. Somewhat – what exactly are they proposing? Are they building such a
ci as they describe or calling for it to be built? How is what they
call for different from what’s already out there?

**Comment by sishtiaq** [comment]
See https://github.com/tomcrick/JORS2015/commit/3fd3e1358ff540fcb536441403b058f64fa84465, which deals with #5 and might also deal with this.

**Comment by hallba** [comment]
I think that we have answered this in the relationships between benchmarks and the CI. I think though that an addition of a list of tasks that we want done would help i.e.

1) De-novo CI (automated compilation on a clean system)
2) A benchmark library that can be added to
3) Multiple algorithms/implementations that are tested alongside new code to show
a) correctness
b) speed (?)

**Comment by hallba** [comment]
I think this is done; in 3 we explicitly call for a codebase that gets compiled automatically, de novo, that links with databases and allows users to add new models. I think correctness/speed testnig is implicit
