### ISSUE TITLE
Make Link between Sections 2 and 3 more explicit

### ISSUE THREAD

**Issue by sishtiaq** [tomcrick/JORS2015#5]
My greatest concern is that the paper reads as though it were two
separate position pieces merged at the middle. The ten recommendations
do indeed set up the latter half of the paper, but the connection is
somewhat tenuous. There is a single sentence that connects the two
directly. My recommendation as a whole is to slightly rewrite the
paper such that the first portion, with recommendations, includes
*both* recommendations and how an abstract web service (RaaS)
implementation could help researchers reach those recommendations. For
instance, this might take the form of, "Recommendation: ... Solution:
An implementation of RaaS could reduce the difficulty ..." and so
on. While this would likely touch the paper in several places, it
would likely not be terribly invasive. That being said, a simple but
more direct connection between the two sections may also resolve this
adequately.

**Comment by sishtiaq** [comment]
This is maybe a good point, there's a big jump from Section 2 to Section 3. 
Though I feel it's slightly unfair: Sections {2.1,2.2,2.5,2.6,.2.7,2.8, 2.9, 2.10} are all *realized* by Section 3. Maybe an intro to Section 3 could say this.

**Comment by sishtiaq** [comment]
See https://github.com/tomcrick/JORS2015/commit/3fd3e1358ff540fcb536441403b058f64fa84465.
@tomcrick: do you think this bridges the gap between Sections 2 and 3?

**Comment by hallba** [comment]
I think that this has now been addressed. I'm happy to close
